services:
  web-backend:
    build: ./app/backend
    container_name: devop1-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - devop1-network

  db:
    image: mysql:8.0
    container_name: devop1-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d # Auto-runs initialization scripts
    networks:
      - devop1-network

  postgres-airflow:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    networks:
      - devop1-network

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    depends_on:
      - postgres-airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    command: version
    networks:
      - devop1-network

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - postgres-airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    ports:
      - "8080:8080"
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/plugins:/opt/airflow/plugins
    command: webserver
    networks:
      - devop1-network

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - postgres-airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - devop1-network

volumes:
  db_data: # Configures volume mounts for persistent data storage
  airflow_db_data:

networks:
  devop1-network: # Configures network for docker
    driver: bridge