FROM apache/airflow:2.9.1

USER root

# Install zip and unzip for the XAU archiving scripts
RUN apt-get update && \
    apt-get install -y zip unzip && \
    rm -rf /var/lib/apt/lists/*

USER airflow
