#ident "@(#)$Format:LocalFoodAI:app.py:%an:%ae:%ad:%cn:%ce:%cd:%H:%D:%N$"
services:
  web-backend:
    build: ./app/backend
    container_name: devop1-backend
    ports:
      - "${BACKEND_PORT}:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - devop1-network

  db:
    image: mysql:8.0
    container_name: devop1-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - devop1-network

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow-init
    depends_on:
      - db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _PIP_ADDITIONAL_REQUIREMENTS=pymysql cryptography requests pandas mysql-connector-python python-dotenv
    command: version
    networks:
      - devop1-network

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow-webserver
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _PIP_ADDITIONAL_REQUIREMENTS=pymysql cryptography requests pandas mysql-connector-python python-dotenv
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/plugins:/opt/airflow/plugins
      - ./XAU:/opt/airflow/XAU
    command: webserver
    networks:
      - devop1-network

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - db
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _PIP_ADDITIONAL_REQUIREMENTS=pymysql cryptography requests pandas mysql-connector-python python-dotenv
    volumes:
      - ./app/dags:/opt/airflow/dags
      - ./app/logs:/opt/airflow/logs
      - ./app/plugins:/opt/airflow/plugins
      - ./XAU:/opt/airflow/XAU
    command: scheduler
    networks:
      - devop1-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-6.4-latest
    container_name: devop1-zabbix-server
    restart: always
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=${MYSQL_ZABBIX_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "10051:10051"
    depends_on:
      - db
    networks:
      - devop1-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
    container_name: devop1-zabbix-web
    restart: always
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=${MYSQL_ZABBIX_PASSWORD}
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - "${ZABBIX_PORT}:8080"
    depends_on:
      - zabbix-server
    networks:
      - devop1-network

volumes:
  db_data:

networks:
  devop1-network:
    driver: bridge