services:
  web-backend:
    build: ./app/backend
    container_name: devop1-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - devop1-network

  db:
    image: mysql:8.0
    container_name: devop1-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d # Auto-runs initialization scripts
    networks:
      - devop1-network

volumes:
  db_data: # Configures volume mounts for persistent data storage

networks:
  devop1-network: # Configures network for docker
    driver: bridge