#ident @(#)$Format:DEVOP1:kubernetes/manifests/airflow.yaml:%an:%ae:%ad:%cn:%ce:%cd:%H:%D:%N$
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: airflow-webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - image: apache/airflow:2.9.1
        name: webserver
        command: ["airflow", "webserver"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: mysql+pymysql://dev_user:your_db_password_here@db/airflow_db
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: _PIP_ADDITIONAL_REQUIREMENTS
          value: pymysql cryptography
        ports:
        - containerPort: 8080
          name: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: default
spec:
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - image: apache/airflow:2.9.1
        name: scheduler
        command: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: mysql+pymysql://dev_user:your_db_password_here@db/airflow_db
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: _PIP_ADDITIONAL_REQUIREMENTS
          value: pymysql cryptography
